#!/usr/bin/env bash
# Displaying number with an insert of words
nbre=1
while ((nbre != 101))
do
if  [ $((nbre%5))  = 0 ]
then  if [ $((nbre%3)) = 0 ]
then echo "FizzBuzz"
#elif [ $((nbre%3)) != 0 ]
#then echo "Buzz"
#else echo "Fizz"
fi
fi
echo "$nbre"
done
