#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd
while IFS=: read -r f1 f4 f6 f7 f3 f5 f2 
do 
       	echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
 done < /etc/passwd
