#!/usr/bin/env bash
# creating a loop integreting "case" statment for displaying some wordsn

nbre=1
while ((nbre != 21))
do	echo "$nbre"
	case $nbre in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
((nbre++))
done
