#!/usr/bin/env bash  
#A script that gives information about the school file 
if [ "$(find . -type f -name 'school' | wc -l)" -gt 0 ]
then echo "school file exists"
fi
if [ "$(find . -type f -empty -name 'school' | wc -l)" -gt 0 ]
then echo "school file is empty"
else echo "school file is not empty"
fi
if [ "$(find . -type d -name 'school' | wc -l)" = 0 ]
then echo "school is a regular file"
fi
if [ "$(find . -type f -name 'school' | wc -l)" = 0 ] 
then echo "school file does not exist"
fi
