#!/usr/bin/env bash
# Bash script whith several instructions

#Creates the file "/var/run/myscript.pid" containing its PID
echo $$ > /var/run/myscript.pid

#Displays To infinity and beyond indefinitely
i=1
while (( i > 0 ))
do echo "To infinity and beyond"
	((i++));
	sleep 2
done
#Displays I hate the kill command when receiving a SIGTERM signal
trap 'echo "I hate the kill command"' SIGTERM 

#Displays Y U no love me?! when receiving a SIGINT signal
trap 'echo "Y U no love me?!"' SIGINT 

#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
#trap 'rm /var/run/myscript.pid' SIGQUIT; SIGTERM
