#!/usr/bin/env bash
#program that manage le script's file
myproc=/var/run/my_process.pid
start() {
	./manage_my_process & 
	echo "$!" > "$myproc"
}
stop() {
	sudo kill -15 "$(cat $myproc)" && rm "$myproc"
}

# $1 c'est la valeur du process start et stop 
case $1 in 
	start)
		start
		echo "manage_my_process started"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		stop
		start 
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac

#on quitte tous les services start stop
exit 0

